angular.module('app.directive', [])
  .directive('ngNavbar', require('./navbar'))
  .directive('ngSide', require('./side'))
  .directive('ngPager', require('./pager'))
  .directive('ngLoading', require('./loading'))
  .directive('ngConfirm', require('./confirm'))